#!/usr/bin/python

print 'Content-type:text/html\r\n\r\n'
print '<html>'
print '<head>'
print '<title>Big 5 - Character Generator</title>'
print '  <style type=\'text/css\'>'
print '    p, li {font-family: \'Roboto\', sans-serif; font-weight: 300; }'
print '  </style>'
print '</head>'
print '<body>'
print '<H1>TITLE!!!</H1>'
print '</body>'
print '<body>'
print '</html>'
